### ISSUE TITLE
Define how the specification should deal with errors/failures

### ISSUE THREAD

**Issue by lavaleri** [awslabs/aws-encryption-sdk-specification#11]
Throughout certain parts of the spec, we prescribe how successes should behave, but not failures/errors, or what failing to meet the requirements of the behavior means. (For example, when defining the keyring OnDecrypt behavior, we do not state what should happen when decryption is attempted but failed)

While it might be ok for the spec to be quiet about failure behaviors, this should be a deliberate choice. We need to identify areas of the spec which are inconsistent/ambigous regarding error/failure cases, and we should make a decision as to whether we definitely want to specify something about that behavior, or whether we want to leave these parts open to implementation, and the consequences of each.

Acceptance criteria:
- team alignment on spec direction regarding error cases
- new issues created to address problem spots in spec.

**Comment by mattsb42-aws** [comment]
This also involves:

* #87
* #76
* #75
