### ISSUE TITLE
Streaming API: Validate the signature before decryption of the final frame?

### ISSUE THREAD

**Issue by seebees** [awslabs/aws-encryption-sdk-specification#113]
The Streaming API MUST validate the GCM tag
before returning any data.
But with the last chunk of data,
the ESDK has the opportunity to verify the signature BEFORE
even attempting the decrypt.

For small messages this seems preferable.
For streaming messages it also seems preferable,
as this means that a fully decrypted message is not return
and then an error is thrown.

**Comment by lavaleri** [comment]
Completed in #149
