### ISSUE TITLE
Add ESDK Concepts to specification

### ISSUE THREAD

**Issue by lavaleri** [awslabs/aws-encryption-sdk-specification#13]
During team review we got feedback that information pertaining to general concepts that the ESDK uses (such as envelope encryption) could be useful for understanding the ESDK.

Acceptance criteria:
- Get team alignment on what scope of this information belongs in the spec and where
- Write it down in the spec

**Comment by seebees** [comment]
Examples
* Correct by construction
* Defaults (rational vs enforced clarity)

**Comment by seebees** [comment]
Resolving because of #160 for now.
