### ISSUE TITLE
Update spec Definitions sections

### ISSUE THREAD

**Issue by lavaleri** [awslabs/aws-encryption-sdk-specification#14]
During the team review we received feedback that the spec should include an overarching definitions section that includes definitions for "byte", define our big endian use, and have one place for defining different algorithms mentioned throughout the document. Given that our specification is across several documents, what is the best way to introduce these definitions?

Acceptance criteria:
- team alignment on way forward for defining general concepts and things defined on specific documents
- Update Definitions sections of documents and/or add overall Definitions section

**Comment by seebees** [comment]
I am closing this in favor of #13.
I think that while there may be some value here,
I would prefer to fill these definitions from external customer feedback.
I think it is too likely that we will attempt to over optimize
the level of detail required.

The example given of byte or unsigned or endianness,
while important the AWS Encryption SDK specification
should not attempt to derive itself from computer science first principles.

So as we find genuine customer confusion 
that requires clearer global definitions these can be added.
