### ISSUE TITLE
Write specification for KMS single client supplier

### ISSUE THREAD

**Issue by lavaleri** [awslabs/aws-encryption-sdk-specification#15]
Write a specification for the KMS single client supplier.

Acceptance criteria:
- Spec contains document specifying single client supplier

**Comment by acioc** [comment]
I believe it would be valuable to have a specification note on what client suppliers we provide "by default" in each ESDK, as well as the customizable functionality we provide for our client suppliers.

**Comment by acioc** [comment]
Closing in favor of https://github.com/awslabs/aws-encryption-sdk-specification/issues/165
