### ISSUE TITLE
EDK Key Provider ID/Information field names

### ISSUE THREAD

**Issue by lavaleri** [awslabs/aws-encryption-sdk-specification#21]
Currently we use the terms "key provider ID" and "Key Provider Information" for fields of the EDK, however these terms don't exactly describe what we want. The implemented keyrings specifically produce EDKs that use these fields to store the "Key Name" and "Key Namespace".

Should we continue with the old "key provider ID" and "key provider information" terms, or should we update them to more accurately represent the data those fields should be capturing?

Acceptance criteria:
- Get team alignment on above question.
- If latter, get team alignment on name change and update spec to reflect new name.

**Comment by mattsb42-aws** [comment]
also affects:

* #47
