### ISSUE TITLE
Add streaming encrypt spec 

### ISSUE THREAD

**Issue by ttjsu-aws** [awslabs/aws-encryption-sdk-specification#26]
Update Encrypt API to include specification of operation in streaming context (i.e. how should this operate in chunks, not requiring everything in memory?)

Current gap:
- How should calculation of the signature (if included in alg suite) be performed?
- How/when should ciphertext be released?
- How/when does the EC become available?
- Various inputs effects' on streaming behavior
- Implications on memory required to be buffered
- Edge cases with possible language specific streaming constructs (i.e. make sure spec covers behavior if a stream is flushed or closed)

**Comment by lavaleri** [comment]
Completed in #149
