### ISSUE TITLE
Provider Info serialization in the AES Keyring/MKP

### ISSUE THREAD

**Issue by ttjsu-aws** [awslabs/aws-encryption-sdk-specification#29]
We want to revisit the provider info serialization in the AES keyring and possibly get rid of it, this is a backlog item that we are leaving as a TODO. This design change has a big surface area and needs to replicated across all implementations.

**Comment by mattsb42-aws** [comment]
IMO the right place to do this is whenever we finally design and build the replacement for raw keyrings.

**Comment by mattsb42-aws** [comment]
This represents a new feature request, so is not necessary for the current scope of spec work.

I've created #132 to track this feature request.
