### ISSUE TITLE
If EC has no elements, update single header field with the value 0 indicating no elements 

### ISSUE THREAD

**Issue by ttjsu-aws** [awslabs/aws-encryption-sdk-specification#3]
Fix:  https://github.com/aws/aws-encryption-sdk-c/blob/master/source/enc_ctx.c#L78

**Comment by seebees** [comment]
The specification is clear and the C ESDK has been fixed
https://github.com/aws/aws-encryption-sdk-c/blob/master/source/enc_ctx.c#L90
