### ISSUE TITLE
Verification of version and type on deserialization base64 encoding error

### ISSUE THREAD

**Issue by seebees** [awslabs/aws-encryption-sdk-specification#42]
When deserializing an encrypted blob.
The version and type are fixed.
However binary data is often stored as a base64 encoded string.
This is especially true of the AWS Encryption SDK Java functions `encryptString`.

Customers will take a base64 encoded string and pass this to a `decrypt` function without the proper decoding, resulting in a failure.

Since the version and type are fixed,
and these values can be translated into their base64 equivalent,
when the blob is rejected as invalid,
the notification can suggest that this failure is an encoding issue.

This may be codified into the specification
or as a recommendation for implementations.

Changes needed:

- [ ] Specification
- [ ] Javascript:
https://github.com/awslabs/aws-encryption-sdk-javascript/pull/217
- [ ] C
https://github.com/aws/aws-encryption-sdk-c/issues/445
- [ ] CLI
https://github.com/aws/aws-encryption-sdk-cli/issues/162
- [ ] Java
https://github.com/aws/aws-encryption-sdk-java/issues/124
- [ ] Python
https://github.com/aws/aws-encryption-sdk-python/issues/192

**Comment by acioc** [comment]
Implementation recommendations?
