### ISSUE TITLE
Define behavior for a KMS-Keyring when given an generator which is an alias

### ISSUE THREAD

**Issue by MatthewBennington** [awslabs/aws-encryption-sdk-specification#49]
Presently the spec [OnEncrypt](https://github.com/awslabs/aws-encryption-sdk-specification/blob/master/framework/kms-keyring.md#onencrypt) section of the spec says that the keyring should use a "client that calls the AWS region specified in the generator ARN".

In cases where the keyring's generator is an alias (e.g. "alias/MyCryptoKey"), there is no way to determine the region to make call is.

**Comment by seebees** [comment]
This is also true for the keyIds as well.  Notes are in the PR, but this is not a generator specific problem

**Comment by acioc** [comment]
Closing in favor of https://github.com/awslabs/aws-encryption-sdk-specification/issues/165
