### ISSUE TITLE
Contradictory MUSTs in Caching CMM

### ISSUE THREAD

**Issue by RustanLeino** [awslabs/aws-encryption-sdk-specification#58]
The specification of the Caching CMM (`framework/caching-cmm.md`) says about the Get Encryption Materials behavior:

> If the algorithm suite requested contains a Identity KDF,

then both

> the caching CMM MUST add the encryption materials obtained from the underlying CMM into the underlying CMC.

and

> the caching CMM MUST NOT store the encryption materials in the underlying CMC.

These two are each other's negations. (Should there have been a "not" in the antecedent of the first of these?)

The same issue is found under Decrypt Materials (with an additional typo, "adds").

**Comment by mattsb42-aws** [comment]
>  the caching CMM MUST add the encryption materials obtained from the underlying CMM into the underlying CMC.

This needs to be a MUST NOT.

We do not cache when the algorithm suite uses the identity KDF and these are meant to safeguard that.

**Comment by RustanLeino** [comment]
Aha, thanks. So, then the sentence that incorrectly says "MUST" should just be deleted (since the second sentence correctly says "MUST NOT").

**Comment by alex-chew** [comment]
Closing as resolved by PR #88 (commit 4c13dc6577234ac9420bd9d499dad4ecf6a8dcd6).
