### ISSUE TITLE
AWS KMS Keyring SHOULD add custom identifier to KMS client user agent string

### ISSUE THREAD

**Issue by mattsb42-aws** [awslabs/aws-encryption-sdk-specification#59]
AWS KMS Keyrings SHOULD add a unique identifier to the user agent string in the KMS client that they use.

The user agent string should uniquely identify the library language and version. For example, the AWS Encryption SDK for Python adds `AwsEncryptionSdkPython/${VERSION}`.

https://github.com/aws/aws-encryption-sdk-python/blob/0f4dc6e7f695191daf3d8ceeef8786a93388259d/src/aws_encryption_sdk/identifiers.py#L31

Adding this value to the user agent is done on a best-effort basis. If the user provides a custom KMS client, the keyring MUST NOT modify that client.

**Comment by acioc** [comment]
Closing in favor of https://github.com/awslabs/aws-encryption-sdk-specification/issues/165
