### ISSUE TITLE
RawRSAKeyring OnDecrypt inconsistent with Keyring Interface

### ISSUE THREAD

**Issue by lavaleri** [awslabs/aws-encryption-sdk-specification#63]
The RawRSAKeying spec says that during OnDecrypt, if there is no private key, OnDecrypt MUST fail. However, the Keyring interface spec says that if no “Decrypt behavior” is attempted, then the decryption materials MUST output the decryption materials unmodified.

Because the RawRSAKeyring MUST also implement the Keyring interface, these statements are not compatible.

We need to determine what the correct behavior is for the RawRSAKeyring is in the case that no private key is available, but the edk list supplied to OnDecrypt is empty.

**Comment by robin-aws** [comment]
I recall some conversation about this, and I'm convinced that "output the decryption materials unmodified" is the correct behaviour.

`OnDecrypt` is essentially a "for each edk, try to decrypt", and in that analogy it usually makes sense to say that pseudocode like `foreach x in list { panic }` should not in fact panic.

**Comment by MatthewBennington** [comment]
The keyring interface and out philosophy around failures have changed enough that this issue is no longer a concern.
