### ISSUE TITLE
clarify naming of AWS KMS keyring

### ISSUE THREAD

**Issue by mattsb42-aws** [awslabs/aws-encryption-sdk-specification#67]
We currently just call the AWS KMS keyring the "KMS keyring". AWS KMS is not the only thing called "KMS". We should be explicit in our naming.

**Comment by juneb** [comment]
Please add a 'doc impact' label to this issue.

**Comment by mattsb42-aws** [comment]
Updating here: we agreed that we want to do this prior to releasing keyrings in Java and Python.

**Comment by acioc** [comment]
Closing in favor of tracking issue: https://github.com/awslabs/aws-encryption-sdk-specification/issues/127
