### ISSUE TITLE
Caching CCM should be clear about who provides the value for Cache TTL

### ISSUE THREAD

**Issue by seebees** [awslabs/aws-encryption-sdk-specification#79]
https://github.com/awslabs/aws-encryption-sdk-specification/blob/master/framework/caching-cmm.md#cache-limit-ttl

This leaves it up to the implementer as to how the CMM will set this value.
But the intention is that the this value is set by the user.
So there should not be a default value.
Since we can not know what a sane default value would be for customer data.

**Comment by alex-chew** [comment]
Resolved by #176.
