### ISSUE TITLE
Raw RSA keyring public/private key inputs and validation

### ISSUE THREAD

**Issue by mattsb42-aws** [awslabs/aws-encryption-sdk-specification#91]
There are a few points that we need to clarify regarding the raw RSA keyring inputs:

* It MUST accept a public key without a private key.
  * In this case the keyring MUST do nothing on decrypt.
* It MUST accept a private key without a public key.
  * In this case the keyring MUST cause encryption to stop.
* It MUST accept both a private key and a public key.
  * Now captured in #167 ~In this case the keyring SHOULD check to make sure that they are part of the same pair.~
    * ~If the keyring does this check and finds that they are not, it MUST cause initialization to stop.~

**Comment by juneb** [comment]
Same meaning. Slightly different words:

* It MUST accept both a private key and a public key.
  * In this case, the keyring SHOULD verify that the keys are in same key pair.
    * If the keyring determines that the keys are _not_ in the same key pair, it MUST throw an error that stops execution.

**Comment by robin-aws** [comment]
Either "halting error" or "stops execution" sounds too severe for me. That seems to imply stopping the whole executing process (e.g. a Java `System.exit()`) which seems an overreaction.

It should be more than enough to just fail to construct the keyring. That will be easy to specify in the documentation for a particular language, but I'm not sure how to word it in the specification. To date we just state requirements directly, such as "If the list of children keyrings is empty, a generator keyring MUST be defined for the keyring" for a multi-keyring. Maybe we should state this in a similar way.

**Comment by seebees** [comment]
The JS ESDK does not do nothing.
If it does not have a public key,
it will throw on encrypt.

**Comment by mattsb42-aws** [comment]
Agreed; failing on encrypt if the public key is not available is the correct thing to do. I've updated the description to correct that.

**Comment by seebees** [comment]
Hum, even on decrypt it should throw.
If it does not, then the customer could get a strange error,
because the material will not have a plaintext data key,
but it will not know why.

This is similar to #40 i.e. if wrapped in a multi keyring (or even on its own)
this error is not helpful and far from the source :(

**Comment by MatthewBennington** [comment]
|                | Encrypt | Decrypt |
|----------------|---------|---------|
| No Private Key | attempt | no-op?  |
| No Public Key  | fail    | attempt |

Need to determine exactly what the behavior in the "no private key - decrypt" case should be. We should aim for consistency among the keyrings, so this should depend on the outcome of #40.

**Comment by mattsb42-aws** [comment]
IMO the behavior should be symmetrical. If we do not want to decrypt if we do not have an explicit public key, we should fail, not no-op.

**Comment by MatthewBennington** [comment]
I assume you mean private key?

I think I agree wit that statement. However, it is in conflict with the current Keyring Interface specification.

> If the keyring did not attempt [to decrypt a datakey], the keyring MUST output the decryption materials unmodified.

This is captured in #63.

**Comment by MatthewBennington** [comment]
Synced offline: that element of the keyring-interface is going to be changed soon. Failure makes the most sense.
