### ISSUE TITLE
define client supplier interface and common manifestations

### ISSUE THREAD

**Issue by mattsb42-aws** [awslabs/aws-encryption-sdk-specification#94]
Related to #15, #16, and #90: we have never really defined anything about client suppliers beyond "they supply clients"[1]. This has resulted in a lot of churn and cases of implementations leading the spec rather than implementing the spec.

We need to at least define:
- [ ] What is a client supplier's role/purpose?
- [ ] What is the client supplier interface?
- [ ] What client suppliers are part of the "standard framework" and what are their interfaces and behaviors?

[1] https://github.com/awslabs/aws-encryption-sdk-specification/blob/master/framework/kms-keyring.md#client-supplier

**Comment by mattsb42-aws** [comment]
One point we need to make sure we hit in here is: what does a caching client supplier do and why.

**Comment by acioc** [comment]
Closing in favor of https://github.com/awslabs/aws-encryption-sdk-specification/issues/165
